apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
  namespace: car-rent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      containers:
      - name: ai-chatbot
        image: ai-chatbot:latest # Replace with your image repo if pushing to registry
        ports:
        - containerPort: 8000
