apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot-service
  namespace: car-rent-app
spec:
  selector:
    app: ai-chatbot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
